#!/bin/bash
# Short script to open TMUX console with a pane for each robot or docker container
# Assumptions:
# - tmux is installed 
# - docker is running containers with names "ethereum_eth.{ID}"
source experimentconfig.sh

# ip a | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep "172." | grep -v .255

NUM_ROB=10

# Collect all containers in a list
ALL_CTS=()
for ID in $(seq 1 $NUM_ROB); do
	ALL_CTS+=($(docker ps -q -f name="ethereum_eth.${ID}\."))
done


tmux_ALL() {
	# Create an sequence of split window action for each container ID
	split_list=()
	for CT in "${ALL_CTS[@]:1}"; do
	    split_list+=( split-pane docker exec -it "$CT" /bin/bash ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new -s $1 docker exec -it "${ALL_CTS[0]}" /bin/bash ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 
}

tmux_ALL_logs() {
	# Create an sequence of split window action for each container ID
	split_list=()
	for ID in $(seq 2 $NUM_ROB); do
	    split_list+=( split-pane tail -f "${EXPERIMENTFOLDER}"/logs/"${ID}"/"$2" ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new -s $1 tail -f "${EXPERIMENTFOLDER}"/logs/"1"/"$2"  ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 
}

tmux_ALL_geth_logs() {
	# Create an sequence of split window action for each container ID
	split_list=()
	for ID in $(seq 2 $NUM_ROB); do
	    split_list+=( split-pane docker logs --tail 2000 --follow $(docker ps -q -f name="ethereum_eth.${ID}\.") ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new -s $1 docker logs --tail 2000 --follow $(docker ps -q -f name="ethereum_eth.1\.")  ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 
}



if [[ $# -eq 0 ]]; then 
	tmux kill-session -t BASH >/dev/null 2>&1
	tmux_ALL "BASH"
fi


if [[ $# -ge 1 ]]; then 
	if [[ $1 == "logs" ]]; then
		tmux kill-session -t LOGS >/dev/null 2>&1
		tmux_ALL_logs "LOGS" monitor.log

		if [[ $# -eq 2 ]]; then
			if [[ $2 == "geth" ]]; then
				tmux kill-session -t LOGS-GETH >/dev/null 2>&1
				tmux_ALL_geth_logs "LOGS-GETH"
			else
				tmux kill-session -t LOGS >/dev/null 2>&1
				tmux_ALL_logs "LOGS" $2
			fi
		fi

	elif [[ $1 == "geth" ]]; then
	tmux kill-session -t GETH >/dev/null 2>&1
 	tmux_ALL "GETH"
	tmux send-keys -t GETH "bash geth_attach.sh" Enter

    elif [[ $1 == "python" ]]; then
	tmux kill-session -t PYTHON >/dev/null 2>&1
	tmux_ALL "PYTHON"
	tmux send-keys -t PYTHON "python3 -i /root/python_scripts/console_robot.py Estimation.abi" Enter
    fi
fi
