#!/bin/bash
# Start an experiment
source experimentconfig_single.sh

# argos_configuration() {
#     marker="/r/"

#     grep -o -P '(?<=$marker).*(?=$marker)' $ARGOSTEMPLATE | while read -r match ; do
#         if [[ ! -n "$match" ]]; then
#             echo "Please add $match to experimentconfig.sh"
#         fi
#     done
#    # sed -e "s|${marker}match${marker}|$match|g" $ARGOSTEMPLATE > $ARGOSFILE
# }

echo "+-----------------------------------------------------------+"
echo "MAINFOLDER IS $MAINFOLDER"

echo "+-----------------------------------------------------------+"
echo "Updating the ARGoS XML file"

sed -e "s|NUMROBOTS|$NUMROBOTS|g"\
    -e "s|CONTROLLER|$CONTROLLER|g"\
    -e "s|NUM1|$NUM1|g"\
    -e "s|NUM2|$NUM2|g"\
    -e "s|STARTDIM|$STARTDIM|g"\
    -e "s|TPS|$TPS|g"\
    -e "s|RABRANGE|$RABRANGE|g"\
    -e "s|NUMBYZANTINE|$NUMBYZANTINE|g"\
    -e "s|EXPERIMENTFOLDER|$EXPERIMENTFOLDER|g"\
    -e "s|FLOORFILE|$FLOORFILE|g"\
    -e "s|ARGOSFOLDER|$ARGOSFOLDER|g"\
    -e "s|ARENADIMXH|$ARENADIMXH|g"\
    -e "s|ARENADIMYH|$ARENADIMYH|g"\
    -e "s|ARENADIMX|$ARENADIMX|g"\
    -e "s|ARENADIMY|$ARENADIMY|g"\
  $ARGOSTEMPLATE > $ARGOSFILE



echo "+-----------------------------------------------------------+"
echo "Cleaning logs folder..."
source experimentconfig_single.sh

# Keep files 0-$NUMROBOTS in order to prevent having to reopen logs
eval $(echo "rm -rf logs/{$(($NUMROBOTS+1))..100}")

if [[ $2 == "--start" ]]; then
    echo "+-----------------------------------------------------------+"
    echo "Starting Experiment-GUI"

    argos3 -c $ARGOSFILE
fi

if [[ $2 == "--start-novis" ]]; then
    echo "+-----------------------------------------------------------+"
    echo "Starting Experiment"

    argos3 -z -c $ARGOSFILE
fi