#!/bin/bash  
# Short script to extract and store log files

source experimentconfig.sh

LOGSFOLDER="$EXPERIMENTFOLDER/logs/"
DATAFOLDER="$EXPERIMENTFOLDER/results/data/experiment_$1/"
PLOTFOLDER="$EXPERIMENTFOLDER/results/plots/experiment_$1/"

# Create the experiment directory
mkdir -p $LOGSFOLDER $DATAFOLDER $PLOTFOLDER

# Find the latest repetition in that folder
last_rep=$(ls $DATAFOLDER -v | tail -1 | sed 's/^0*//')
new_rep=$(printf "%03d\n" $(($last_rep+1)))

# Collect experiment configuration into /logs/
python3 collect-config.py
cp experimentconfig.sh $LOGSFOLDER
cp $EXPERIMENTFOLDER/loop_functions/loop_params.py $LOGSFOLDER
cp $EXPERIMENTFOLDER/controllers/control_params.py $LOGSFOLDER

# Collect geth related logs from docker folder into /logs/
for ID in $(seq 1 $NUMROBOTS); do
  cp -rp $DOCKERFOLDER/geth/logs/$ID/ $LOGSFOLDER
done

# Collect data from /logs/ into /results/data
cp -rp $LOGSFOLDER $DATAFOLDER$new_rep

echo "Storing data to: /results/data/experiment_$1/$new_rep"

