#!/bin/bash  
# Short script to extract log files from all robots listed
# Assumptions:
# - The Pi-puck IDs are listed in pi-pucks.txt
source experimentconfig_backup.sh

# if [ "$#" -eq 1 ]; then

# 	if [ -d "$EXPERIMENTFOLDER/results/data/$1" ]; then
# 		# Take action if $DIR exists. #
# 		echo "Rewrite folder $EXPERIMENTFOLDER/results/data/$1? [Y/N]"
# 		read CONF
# 	if [ $CONF = "Y" -o $CONF = "y" ]; then
# 		rm -rfv $EXPERIMENTFOLDER/results/data/$1
# 	else
# 		exit 1
# 	fi
# 	fi
# fi	



# Create the experiment directory
mkdir -p $EXPERIMENTFOLDER/logs/ $EXPERIMENTFOLDER/results/data/experiment_$1

# Find the latest repetition in that folder
last_rep=$(ls results/data/experiment_$1/ -v | tail -1 | sed 's/^0*//')
new_rep=$(printf "%03d\n" $(($last_rep+1)))

# Collect geth related logs from docker folder
cp -rp $DOCKERFOLDER/geth/logs/* $EXPERIMENTFOLDER/logs/

# Collect argos related logs from experiment folder
cp -rp $EXPERIMENTFOLDER/logs/ $EXPERIMENTFOLDER/results/data/experiment_$1/$new_rep

echo "Storing data to: /results/data/experiment_$1/$new_rep"

# backup
# if [ "$#" -eq 1 ]; then
# 	rm -rfv $MAIN_DIR/results/data/$1 && mkdir -p $MAIN_DIR/results/data/$1
# 	for ID in $(cat "$IDS_FILE"); do
# 		scp -r pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/control/robots/logs $MAIN_DIR/results/data/$1/$ID
# 	done
# else
# 	echo "Input record foldername"
# fi