#!/bin/bash
 
source experimentconfig.sh

echo "+-----------------------------------------------------------+"
echo "Updating the Smart Contract"

sed -e "s|MAXSTAKERS|$MAXSTAKERS|g"\
    -e "s|MAXWORKERS|$MAXWORKERS|g"\
    -e "s|STAKERSHARE|$STAKERSHARE|g"\
    -e "s|WORKERSHARE|$WORKERSHARE|g"\
    -e "s|EPSILON|$EPSILON|g"\
    -e "s|WINSIZE|$WINSIZE|g"\
  $SCTEMPLATE > $SCFILE

echo "+-----------------------------------------------------------+"
echo "Compiling the Smart Contract"

# Compile smart contract
solc --overwrite --abi --bin-runtime -o  "${EXPERIMENTFOLDER}/scs/build/" $SCFILE
cp -r "${EXPERIMENTFOLDER}/scs/build/." "${DOCKERFOLDER}/geth/deployed_contract/"

BINDATA=`cat ${CONTRACTBIN}`

echo "+-----------------------------------------------------------+"
echo "Generating the Genesis block"

# Create genesis using puppeth
bash ${DOCKERFOLDER}/geth/files/reset-genesis ${NUMROBOTS} $BLOCKPERIOD

# Insert the smart contract into the genesis 
sed -ie "s|123\": {|123\": {\n\"code\": \"0xBINDATA\",|g" ${GENESISFILE}
sed -ie "s|BINDATA|$BINDATA|g" ${GENESISFILE}
# Change the gas limit
sed -ie "s|0x47b760|0x9000000000000|g" ${GENESISFILE}
# Change the value of the pre-funded accounts
sed -ie "s|\"0x200000000000000000000000000000000000000000000000000000000000000\"|\"0x1236efcbcbb340000\"|g" ${GENESISFILE}
# # Undo for the contract account (first match)
sed -ie "0,/\"0x1236efcbcbb340000\"/s//\"0x200000000000000000000000000000000000000000000000000000000000000\"/" ${GENESISFILE}

# 0x1236efcbcbb340000 = 21 ether
# 0xde0b6b3a7640000 = 1 ether

echo "+-----------------------------------------------------------+"
echo "Restarting the docker containers"


## Restart docker
docker service scale ${CONTAINERBASE}=0
echo "Shuting down docker process..."
bash ${DOCKERFOLDER}/local_scripts/stop_network.sh $NUMROBOTS

echo "Starting new docker process..."
sudo systemctl restart docker.service
bash ${DOCKERFOLDER}/local_scripts/start_network.sh $NUMROBOTS

echo "+-----------------------------------------------------------+"
echo "Creating the identifier file"

## Create identifiers file
# Get IDs
seq 1 $NUMROBOTS > temp0.txt
# Get containers
docker ps --format '{{.Names}} {{.ID}}' > temp1.txt
sort -o temp1.txt temp1.txt
# Get IPs
./bash-all -s "ip a" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep "172." | grep -v ".255" > temp2.txt
./bash-all -s "ip a" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep "10."  | grep -v "10.0.0" | grep -v ".255" > temp3.txt
# Save to identifiers file
paste temp0.txt temp1.txt temp2.txt temp3.txt > identifiers.txt
rm temp0.txt temp1.txt temp2.txt temp3.txt