#!/bin/bash
 
source experimentconfig_backup.sh

## Restart docker
docker service scale ethereum_eth=0
echo "Shuting down docker process..."
bash ${DOCKERFOLDER}/local_scripts/stop_network.sh $NUMROBOTS

echo "Starting new docker process..."
# sudo systemctl restart docker.service
bash ${DOCKERFOLDER}/local_scripts/start_network.sh $NUMROBOTS