#!/bin/bash
# Start an experiment
source experimentconfig.sh

echo "+-----------------------------------------------------------+"
echo "MAINFOLDER IS $MAINFOLDER"

echo "+-----------------------------------------------------------+"
echo "Updating the ARGoS XML file"

sed -e "s|NUMROBOTS|$NUMROBOTS|g"\
    -e "s|CON1|$CON1|g"\
    -e "s|CON2|$CON2|g"\
    -e "s|NUM1|$NUM1|g"\
    -e "s|NUM2|$NUM2|g"\
    -e "s|STARTDIM|$STARTDIM|g"\
    -e "s|TPS|$TPS|g"\
    -e "s|RABRANGE|$RABRANGE|g"\
    -e "s|NUMBYZANTINE|$NUMBYZANTINE|g"\
    -e "s|EXPERIMENTFOLDER|$EXPERIMENTFOLDER|g"\
    -e "s|FLOORFILE|$FLOORFILE|g"\
    -e "s|ARGOSFOLDER|$ARGOSFOLDER|g"\
    -e "s|ARENADIMH|$ARENADIMH|g"\
    -e "s|ARENADIM|$ARENADIM|g"\
  $ARGOSTEMPLATE > $ARGOSFILE

if [[ $1 == "--reset-geth" ]]; then

    echo "+-----------------------------------------------------------+"
    echo "Resetting Geth..."
    ./reset-geth
fi

echo "+-----------------------------------------------------------+"
echo "Waiting web3 to respond..."

ready=0
while [[ $ready != $NUMROBOTS ]]; do
    . test-tcp 4000 9898 9899
    sleep 0.5
done

echo "+-----------------------------------------------------------+"
echo "Cleaning logs folder..."

# Keep files 0-$NUMROBOTS in order to prevent having to reopen logs
eval $(echo "rm -rf logs/{$(($NUMROBOTS+1))..100}")

if [[ $2 == "--start" ]]; then
    echo "+-----------------------------------------------------------+"
    echo "Starting Experiment-GUI"

    argos3 -c $ARGOSFILE
fi

if [[ $2 == "--start-novis" ]]; then
    echo "+-----------------------------------------------------------+"
    echo "Starting Experiment"

    argos3 -z -c $ARGOSFILE
fi