#!/bin/bash
# Short script to open TMUX console with a pane for each robot or docker container
# Assumptions:
# - tmux is installed 
# - docker is running containers with names "ethereum_eth.{ID}"
# Options:
# -t list of robot IDs to tmux (string, e.g. "1 2 3 4")
# -n number of robots to tmux  (integer, e.g. 1)
# -c script to be executed     (string, geth, bash, python. Default: bash)
# -l logs to be displayed      (string, monitor.log, sc.csv, estimate.csv, etc. Default: monitor.log)


source experimentconfig.sh

# ip a | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep "172." | grep -v .255

# docker exec -it "$CT" /bin/bash
# $1 docker exec -it "${ALL_CTS[0]}" /bin/bash 

# tail -f "${EXPERIMENTFOLDER}"/logs/"${ID}"/"$2" 
# $1 tail -f "${EXPERIMENTFOLDER}"/logs/"1"/"$2"

# docker logs --tail 2000 --follow $(docker ps -q -f name="ethereum_eth.${ID}\.")
# $1 docker logs --tail 2000 --follow $(docker ps -q -f name="ethereum_eth.1\.")

tmux_ALL() {
	# Create an sequence of split window action for each container ID
	split_list=()
	for CT in "${ALL_CTS[@]:1}"; do
		ID=$(docker ps -f ID=$CT --format "{{.Names}}" | cut -d '.' -f2)
    split_list+=( split-pane docker exec -it "$CT" /bin/bash ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new -s $1 docker exec -it "${ALL_CTS[0]}" /bin/bash ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 
}

tmux_ALL_logs() {
	# Create an sequence of split window action for each container ID
	split_list=()
	for CT in "${ALL_CTS[@]:1}"; do
		ID=$(docker ps -f ID=$CT --format "{{.Names}}" | cut -d '.' -f2)
	  split_list+=( split-pane tail -f "${EXPERIMENTFOLDER}"/logs/"${ID}"/"$2" ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new -s $1 tail -f "${EXPERIMENTFOLDER}"/logs/"1"/"$2"  ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 
}

tmux_ALL_geth_logs() {
	# Create an sequence of split window action for each container
	split_list=()
	for CT in "${ALL_CTS[@]:1}"; do
			ID=$(docker ps -f ID=$CT --format "{{.Names}}" | cut -d '.' -f2)
	    split_list+=( split-pane docker logs --tail 2000 --follow $CT ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new -s $1 docker logs --tail 2000 --follow "${ALL_CTS[0]}"  ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 
}


NUM_ROB=""
TARGETS=""
SCRIPT="bash"
LOGS="geth"

while getopts ":n:t:c:l:" opt; do

  case ${opt} in

    t ) # process option t
			TARGETS=${OPTARG}
      ;;
    n ) # process option n
			NUM_ROB=${OPTARG}
			;;
    c ) # process option c
			SCRIPT=${OPTARG}
      ;;
    l ) # process option l
			LOGS=${OPTARG}
      ;;
    \? ) echo "Usage: cmd [-t] [-n] [-c] [-l]"
      ;;

  esac
done


if [ "$NUM_ROB" = "" ]; then
	NUM_ROB=$(docker ps | grep ethereum_eth. | wc -l) 
fi

if [ "$TARGETS" = "" ]; then
	ALL_IDS=()
	ALL_CTS=()
	for ID in $(seq 1 $NUM_ROB); do
		ALL_IDS+=(${ID})
		ALL_CTS+=($(docker ps -q -f name="ethereum_eth.${ID}\."))
	done

else
	ALL_IDS=()
	ALL_CTS=()
	for ID in $TARGETS; do
		ALL_IDS+=(${ID})
	  ALL_CTS+=($(docker ps -q -f name="ethereum_eth.${ID}\."))
	done
	NUM_ROB=${#ALL_IDS[@]}

fi


if [ "$SCRIPT" = "bash" ]; then 
	echo $SCRIPT
	tmux kill-session -t BASH >/dev/null 2>&1
	tmux_ALL "BASH"

elif [ "$SCRIPT" = "python" ]; then 
	echo $SCRIPT
	tmux kill-session -t PYTHON >/dev/null 2>&1
	tmux_ALL "PYTHON"
	tmux send-keys -t PYTHON "python3 -i /root/python_scripts/console_robot.py Estimation.abi" Enter

elif [ $SCRIPT = "geth" ]; then
	tmux kill-session -t GETH >/dev/null 2>&1
 	tmux_ALL "GETH"
	tmux send-keys -t GETH "bash geth_attach.sh" Enter
fi


if [ $LOGS = "geth" ]; then
	tmux kill-session -t LOGS-GETH >/dev/null 2>&1
	tmux_ALL_geth_logs "LOGS-GETH"
else
	tmux kill-session -t LOGS >/dev/null 2>&1
	tmux_ALL_logs "LOGS" $LOGS
fi	

