#!/bin/bash  
# Short script to extract log files from 
# DOCKERFOLDER/geth/logs and EXPERIMENTFOLDER/logs to
# EXPERIMENTFOLDER/results/data/experiment_name/config_name/rep

# Arguments: (string) experiment_name/config_name

source experimentconfig.sh

LOGSFOLDER="$EXPERIMENTFOLDER/logs/"
DATAFOLDER="$EXPERIMENTFOLDER/results/data/experiment_$1/"
PLOTFOLDER="$EXPERIMENTFOLDER/results/plots/experiment_$1/"

# Create the experiment directory
mkdir -p $LOGSFOLDER $DATAFOLDER $PLOTFOLDER

# Find the latest repetition in that folder
last_rep=$(ls $DATAFOLDER -v | tail -1 | sed 's/^0*//')
new_rep=$(printf "%03d\n" $(($last_rep+1)))

# Collect experiment configuration into /logs/
python3 << END
import sys, os

sys.path += [os.environ['EXPERIMENTFOLDER']+'/controllers', \
             os.environ['EXPERIMENTFOLDER']+'/loop_functions', \
             os.environ['EXPERIMENTFOLDER']]

import loop_function_params as lp
import controller_params as cp

# Collect the loop parameters
dict_list = [(param, value) for param, value in lp.params.items() if isinstance(value, dict)]

# Collect the control parameters
dict_list.extend([('control', cp.params)])

# Collect the experiment configuration
f = open('experimentconfig.sh', 'r')
experimentconfig = f.read()
experimentparams = {param:value for param,value in os.environ.items() if param in experimentconfig}
dict_list.extend([('experiment',experimentparams)])

savefile = open(os.environ['EXPERIMENTFOLDER'] + '/logs/config.py', 'w+')
for name, param_dict in dict_list:
  savefile.write('%s = %s \n' % (name, repr(param_dict)))
END

cp experimentconfig.sh $LOGSFOLDER
cp $EXPERIMENTFOLDER/loop_functions/loop_function_params.py $LOGSFOLDER
cp $EXPERIMENTFOLDER/controllers/controller_params.py $LOGSFOLDER

# Collect geth related logs from docker folder into /logs/
for ID in $(seq 1 $NUMROBOTS); do
  cp -rp $DOCKERFOLDER/geth/logs/$ID/ $LOGSFOLDER
done
wait 

# Collect data from /logs/ into /results/data
rm ${LOGSFOLDER}.gitignore
cp -rp $LOGSFOLDER $DATAFOLDER$new_rep

echo "Storing data to: /results/data/experiment_$1/$new_rep"

