#!/bin/bash
# Short script to open TMUX console with a pane for each docker container
# Assumptions:
# - tmux is installed 
# - docker is running containers with names "ethereum_eth.{ID}"
# source ../../globalconfig

# ip a | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep "172." | grep -v .255

NUM_ROB=$(docker ps | grep ethereum_eth. | wc -l) 

# Collect all containers in a list
ALL_CTS=()
for ID in $(seq 1 $NUM_ROB); do
	ALL_CTS+=($(docker ps -q -f name="ethereum_eth.${ID}\."))
done


tmux_ALL() {
	# Create an sequence of split window action for each container ID
	split_list=()
	for CT in "${ALL_CTS[@]:1}"; do
	    split_list+=( split-pane docker exec -it "$CT" /bin/bash ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new-session docker exec -it "${ALL_CTS[0]}" /bin/bash ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 
}

if [[ $# -eq 0 ]]; then 
	tmux_ALL
fi
# elif [[ $# -eq 1 ]]; then 

# 	if [[ $1 == "geth" ]]; then 
# 		tmux_ALL
# 		# Rename to GETH and setup Geth
# 		tmux kill-session -t GETH >/dev/null 2>&1
# 		tmux rename-session GETH
# 		tmux send-keys -t GETH "cd $MAIN_DIR_ROBOTS" Enter "./setup-geth"

# 	elif [[ $1 == "mainloop" ]]; then 
# 		tmux_ALL
# 		# Rename to MAINLOOP and setup mainloop
# 		tmux kill-session -t MAINLOOP >/dev/null 2>&1
# 		tmux rename-session MAINLOOP
# 		tmux send-keys -t MAINLOOP:0.$PANE "cd $MAIN_DIR_ROBOTS/control/robots" Enter "python3 -i mainloop.py --nowalk"

# 	else 
# 		tmux_ALL
# 		# Rename to GETH and setup Geth
# 		tmux kill-session -t GETH >/dev/null 2>&1
# 		tmux rename-session GETH
# 		tmux send-keys -t GETH "cd $MAIN_DIR_ROBOTS" Enter "./setup-geth"
		
# 		tmux_ALL
# 		# Rename to MAINLOOP and setup mainloop
# 		tmux kill-session -t MAINLOOP >/dev/null 2>&1
# 		tmux rename-session MAINLOOP
# 		tmux send-keys -t MAINLOOP:0.$PANE "cd $MAIN_DIR_ROBOTS/control/robots" Enter "python3 -i mainloop.py --nowalk"
# 	fi
# fi